version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.prod
    ports:
      - "5432:5432"
    restart: always

  backend:
    build: ./api
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn api.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./api:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - "8000"
    env_file:
      - .env.prod
    depends_on:
      - db
    restart: always

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    expose:
      - "5173"
    env_file:
      - .env.prod
    depends_on:
      - backend
    restart: always

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/usr/share/nginx/html/static
      - media_volume:/usr/share/nginx/html/media
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - backend
      - frontend
    restart: always

volumes:
  postgres_data:
  static_volume:
  media_volume: 