# Generated by Django 5.1.6 on 2025-03-17 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="cv/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "CV",
                "verbose_name_plural": "CVs",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.RemoveField(
            model_name="portfolio",
            name="image",
        ),
        migrations.CreateModel(
            name="PortfolioImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="portfolio/")),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("ordinal", models.IntegerField(default=0)),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="portfolio.portfolio",
                    ),
                ),
            ],
            options={
                "ordering": ["ordinal"],
            },
        ),
    ]
