# Generated by Django 5.1.6 on 2025-03-17 03:53

import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_cv_remove_portfolio_image_portfolioimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="awards",
            name="image",
            field=models.ImageField(upload_to=portfolio.models.get_file_path),
        ),
        migrations.AlterField(
            model_name="cv",
            name="file",
            field=models.FileField(upload_to=portfolio.models.get_file_path),
        ),
        migrations.AlterField(
            model_name="portfolioimage",
            name="image",
            field=models.ImageField(upload_to=portfolio.models.get_file_path),
        ),
    ]
