# Generated by Django 5.1.6 on 2025-03-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_alter_awards_image_alter_cv_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="title",
            field=models.CharField(default="software", max_length=255),
            preserve_default=False,
        ),
    ]
