# Generated by Django 5.1.6 on 2025-03-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_experience_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aboutme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
            ],
        ),
    ]
