# Generated by Django 5.1.6 on 2025-03-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_aboutme"),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="grade",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
