# Generated by Django 5.1.6 on 2025-03-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_education_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
