# Generated by Django 5.1.6 on 2025-04-22 19:22

import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_experience_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=portfolio.models.get_file_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Profile Image',
                'verbose_name_plural': 'Profile Images',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='awards',
            options={'ordering': ['ordinal']},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['ordinal']},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['ordinal']},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['ordinal']},
        ),
    ]
